development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: "aaron_development"
  pool: 5
  username: root
  password: "000"
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: "aaron_production"
  pool: 5
  username: root
  password: "000"
  socket: /var/run/mysqld/mysqld.sock
